/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "pageClass": "homepage",
        "footer": "© 2019 Aristotle."
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-fb36209e",
      "path": "/",
      "lastUpdated": "5/27/2019, 12:49:07 PM"
    },
    {
      "title": "Aristotle",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-17e9c1c4",
      "path": "/guide/",
      "headers": [
        {
          "level": 3,
          "title": "Monorepo Design",
          "slug": "monorepo-design"
        },
        {
          "level": 2,
          "title": "Prerequisites",
          "slug": "prerequisites"
        },
        {
          "level": 2,
          "title": "Quick start",
          "slug": "quick-start"
        }
      ],
      "lastUpdated": "5/27/2019, 12:49:07 PM"
    }
  ],
  "themeConfig": {
    "logo": "/assets/logo.svg",
    "repo": "jshor/aristotle",
    "docsDir": "docs",
    "editLinks": true,
    "sidebarDepth": 2,
    "locales": {
      "/": {
        "label": "English",
        "selectText": "Languages",
        "lastUpdated": "Last Updated",
        "editLinkText": "Edit this page on GitHub",
        "nav": [
          {
            "text": "Guide",
            "link": "/guide/"
          }
        ],
        "sidebar": [
          {
            "title": "Guide",
            "path": "/guide/"
          }
        ]
      }
    }
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "title": "Aristotle",
      "description": "The digital logic simulator",
      "path": "/"
    }
  }
}