import ItemSubtype from '../enums/ItemSubtype'
import ItemType from '../enums/ItemType'
import ClockPulse from '@/store/document/oscillator/ClockPulse'
import Point from '@/types/interfaces/Point'
import BoundingBox from '../types/BoundingBox'
import BaseItem from './BaseItem'
import IntegratedCircuit from './IntegratedCircuit'
import Property from './Property'
import LogicValue from '../enums/LogicValue'
import ItemProperties from './ItemProperties'

interface Item extends BaseItem {
  type: ItemType
  subtype: ItemSubtype
  /** The default name to refer to this item. */
  defaultName: string
  /**
   * The current defined name to refer to this item.
   * This differs from {@link defaultName} in that it can be changed by the user.
   * It will be auto-generated by the editor when the item is first created.
   */
  name: string
  portIds: string[]
  groupId: string | null
  rotation: number
  boundingBox: BoundingBox
  position: Point
  zIndex: number
  width: number
  height: number
  properties: ItemProperties
  clock?: ClockPulse | null
  integratedCircuit?: IntegratedCircuit
}

export default Item
